name: Admin_Commands
description: PlayzCraft Custom Admin Plugin
author: Ofir Aviel
main: rf.gd.ofir29200.Admin_Commands
version: 9.0
commands:
   lag:
      description: check you lag with the server
      usage: /lag
   shutdown:
      description: admin command (not for players)
      usage: /shutdown [OTP Key]
   override:
      description: admin command (not for players)
      usage: /override [ID Number]
   discord:
      description: get a link to join our discord server
      usage: /discord
   news:
      description: get a link to get to our news webpage
      usage: /news